name: Create Backups

on:
  # Triggers the workflow on schedule
  schedule:
    - cron: "0 0 * * *" # At 00:00 on every day-of-month from 1 through 31.
  # Run this workflow manually.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run main.py
        uses: appleboy/ssh-action@master
        with:
          # VPS
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}

          script: |
            psql-backup/env/bin/python3 psql-backup/main.py
