name: Create Backups

on:
  # Triggers the workflow on schedule
  schedule:
    - cron: "0 0 * * 0" # At 00:00 UTC on every sunday.
  # Run this workflow manually.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run main.py
        uses: appleboy/ssh-action@master
        with:
          # VPS
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}

          script: |
            psql-backup/env/bin/python3 psql-backup/main.py
